apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service-dev
  namespace: dev-namespace
spec:
  selector:
    app: reddit-clone-dev
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer

