apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment-dev
  namespace: dev-namespace
  labels:
    app: reddit-clone-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit-clone-dev
  template:
    metadata:
      labels:
        app: reddit-clone-dev
    spec:
      containers:
      - name: reddit-clone-dev
        image: blesseddocker/reddit-project
        ports:
        - containerPort: 3000
