apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service-prod
  namespace: prod-namespace
spec:
  selector:
    app: reddit-clone-prod
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer