apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment-prod
  labels:
    app: reddit-clone-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit-clone-prod
  template:
    metadata:
      labels:
        app: reddit-clone-prod
    spec:
      containers:
      - name: reddit-clone-prod
        image: blesseddocker/reddit-project
        ports:
        - containerPort: 3000
