apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment-qa
  namespace: qa-namespace
  labels:
    app: reddit-clone-qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit-clone-qa
  template:
    metadata:
      labels:
        app: reddit-clone-qa
    spec:
      containers:
      - name: reddit-clone-qa
        image: blesseddocker/reddit-project
        ports:
        - containerPort: 3000
