apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service-qa
  namespace: qa-namespace
spec:
  selector:
    app: reddit-clone-qa
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer